<?php

return [
    'title' => [
        'generateroutine' => 'Generate Routine',
    ],
    'subtitle' => [
        'generateroutine' => 'Routine Generation Using OpenAI',
    ],
    'prompt' => [
        'intro' => 'Create a personalized exercise routine. Do not extend the response, keep it short and use no more than 1000 characters, based on the following specifications:',
        'user_info' => "User's Name: :name\nUser's Age: :age\nUser's Weight: :weight\nUser's Height: :height\nUser's Gender: :gender",
        'training_info' => "Training Context: :name\nAvailable Time: :time minutes\nTraining Place: :place\nTraining Frequency: :frequency times per week\nTraining Objectives: :objectives\nTraining Specifications: :specifications",
        'exercises' => 'Available Exercises:'
    ],
    'routine' => [
        'generated_name' => 'Routine generated by OpenAI'
    ],
    'button' => [
        'generateroutine' => 'Generate Routine'
    ]
];
